# syntax=docker/dockerfile:1
FROM centos:8
RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf config-manager --set-enabled powertools
RUN dnf -y update
RUN dnf -y group install "Development Tools"
RUN dnf -y install cmake systemd-rpm-macros libpcap-devel libnet-devel \
                         libconfig-devel \
                         mariadb-devel mariadb-connector-c-devel \
                         systemd-devel
RUN dnf -y install python2-pip python3-pip
RUN pip3 install cpplint
